language: php

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: 5.3
    - php: nightly

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
